docs/installation.md

Sublime Text did a bunch of whitespace cleanup, the important bit is line 111-117

Add note about Raspberry Pi baudrate

---

README.md

`require("pixel")` => `require("node-pixel")`
See #25

Update module name in requires

---

docs/installation.md

node-pixel is on npm now! :tada:

Remove npm note

---

examples/np-rainbow-dynamic.js
examples/np-rainbow-static.js

Adding the examples that @ajfisher helped with in issue #31
Also adding a `.gitignore` file

Adding some rainbow color examples

---

lib/pixel.js

Fixes #17
For testing I switched the examples to use .colour.

Aliased .colour to .color

---

README.md

Some proofreading and minor edits. Also, syntax highlighting!

README edits and syntax highlighting

---

README.md
lib/pixel.js
test/core.js

G'day! :raising_hand:
This PR is addressing #54 - to add a `Strip.off` method.
Please feel free to nitpick anything you see and I'll fix it.
I should also add that I don't have any pixels to test with IRL, so haven't verified it.
:smile_cat:

[feature] add Strip.off method

---

lib/pixel.js

If you want black color, should just specify "black".

if `off`, it should latch immediately

---

docs/firmata.md
docs/johnnyfive-i2c.md
docs/johnnyfive.md
docs/multipin-i2c.md
docs/multipin.md
docs/rainbow-dynamic-multipin.md
docs/rainbow-dynamic.md
docs/rainbow-static.md

Update docs to use strip.length

---

package.json

fix(package): update firmata to version 0.19.1

---

package.json

chore(package): update coveralls to version 3.0.1

---

docs/multipin-i2c.md

https://github.com/ajfisher/node-pixel/issues/92#issuecomment-323967403

Update multipin-i2c.md with Raspberry Pi example

---

.huskyrc
Makefile
package-lock.json
package.json

Add husky in order to manage workflow and ensure linting & testing happens before publishing. Also expand test recipe so that node targets are appropriately covered.

chore(ci): Add husky to repo

---

.versionrc

To include more detail than just fix and feature.

build(docs): Added changelog controls to standard-version 

---

Makefile
firmware/src/README.md

Switched make compilation process over to use the official arduino-cli tooling which should allow us to do build testing as well.

feat(build): Updated build process to use arduino-cli

---

.github/workflows/firmware_build.yml

Runs an action on PR in order to test that boards will build correctly.

build: Added github action for testing board compilation

---

README.md

docs: Updated readme to provide extra help for windows users. 

---

.github/workflows/firmware_build.yml

fix(build): Updated Arduino CLI step to new action type

---

lib/pixel.js
test/core.js

simple fix for color object reference issue

fix: gamma object ref

---

docs/johnnyfive-i2c.md
docs/johnnyfive.md
docs/multipin-i2c.md
examples/channel_fade.js
examples/firmata.js
examples/johnnyfive-i2c.js
examples/johnnyfive.js
examples/mega-multipin.js
examples/multipin-i2c.js
examples/multipin.js
examples/panel.js
examples/rainbow-dynamic-multipin.js
examples/rainbow-dynamic.js
examples/rainbow-static.js
examples/repl.js
examples/shift.js

fixes npm paths so gamma fix can be merged to upstream

docs: update all docs to refelct new breakdown
